name: harumanis
description: Beli Harumanis - Buy fresh Harumanis mangoes direct from farms
publish_to: 'none'
version: 1.9.5+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  app_links: ^6.0.0
  camera: ^0.10.5
  timezone: ^0.11.0
  flutter_local_notifications: ^22.0.0-dev.3
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0a1927"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
